### ISSUE TITLE
I would like to try adding a Korean translation to the site. Could you give me permission?

### ISSUE THREAD

**Issue by tastekim** [bonfire-engine/bonfire-engine.github.io#10]
I would like to contribute to the community of casual games made with Flutter through Korean translation work!
I'm working on it personally. Could you please check it if I submit a Pull Request?

**Comment by RafaelBarbosatec** [comment]
Hi @tastekim ! It’s sounds be great! I love this idea!
You can in any moment submitting a pull request.
I'll try adds the structure to support multi-language. https://docsify.js.org/

**Comment by tastekim** [comment]
@RafaelBarbosatec Thank you so much!
I already have some work to do. Can I post a PR? Please advise me on my working methods!
