### ISSUE TITLE
Tiled world maps with gzip/zlib compression not supported on web

### ISSUE THREAD

**Issue by wsv-accidis** [bonfire-engine/bonfire-engine.github.io#16]
## Summary

When building for web, Tiled world maps fail to load when using any kind of compression because the library used for decompression isn't available. Uncompressed Base64 and CSV formats work normally.

## Details

`TileLayer.fromJson` checks for the type of compression used and invokes either `zlib.decode` or `gzip.decode` from `dart:io` to decompress the tiles. However, `dart:io` is intended for native apps and doesn't work when building for web. This is unfortunate as web apps stand to benefit the most from smaller map file sizes.

## Steps to reproduce

1. Create a basic Flutter+Flame+Bonfire project for web.
2. Following the [documentation](https://bonfire-engine.github.io/#/doc/tiled_support?id=tiled-support), try to load any Tiled map that uses compression.
3. Run the project in Chrome.
4. Observe that the map doesn't load.

## Suggested fix

Replace the use of `dart:io` in Bonfire with [universal_io](https://pub.dev/packages/universal_io) which provides the same functionality but supports web. Alternatively, just use [archive](https://pub.dev/packages/archive) for decompressing maps.

**Comment by RafaelBarbosatec** [comment]
Hi Wilhelm!
Thanks for this suggestions!
In the current version already is possible use tiled compression using web
platform.

Em dom, 13 de out de 2024 12:54, Wilhelm Svenselius <
***@***.***> escreveu:

**Comment by wsv-accidis** [comment]
Thank you @RafaelBarbosatec! Also, just realizing now I mistakenly created this issue in the documentation repo instead of the actual Bonfire engine repo. My bad.
