### ISSUE TITLE
The documentation does not explain about the use of simpleAlly

### ISSUE THREAD

**Issue by UR4N0-235** [bonfire-engine/bonfire-engine.github.io#6]
The documentation doesn't talk about how to use [simpleAlly](https://github.com/RafaelBarbosatec/bonfire/blob/master/lib/npc/ally/simple_ally.dart), I assume because it's a new extension or something. But it would be important to explain how to use this to create allies and how to create the basic to interact with players and enemies.

**Comment by RafaelBarbosatec** [comment]
Available in version 3.0 https://bonfire-engine.github.io/#/doc/ally?id=ally
